-- 생성 전 중복 테이블 삭제
DROP TABLE REVIEW_IMAGE CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE DELIVERY CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_ORDER CASCADE CONSTRAINTS;
DROP TABLE WISH CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;

DROP TABLE OPTION_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TAG_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CATEGORY_DETAIL CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IMAGE CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE WALLET CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP TABLE PRODUCT_OPTION CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;

-- 생성 전 중복 시퀀스 삭제
DROP SEQUENCE SEQ_GRADE_ID;
DROP SEQUENCE SEQ_PAYMENT_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_TAG_ID;
DROP SEQUENCE SEQ_COUPON_ID;
DROP SEQUENCE SEQ_OPTION_ID;

DROP SEQUENCE SEQ_MEMBER_ID;
DROP SEQUENCE SEQ_WALLET_ID;
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_PRODUCT_IMAGE_ID;
DROP SEQUENCE SEQ_CD_ID;
DROP SEQUENCE SEQ_TD_ID;
DROP SEQUENCE SEQ_PD_ID;

DROP SEQUENCE SEQ_CART_ID;
DROP SEQUENCE SEQ_WISH_ID;
DROP SEQUENCE SEQ_ORDER_ID;
DROP SEQUENCE SEQ_OD_ID;
DROP SEQUENCE SEQ_DELIVERY_ID;
DROP SEQUENCE SEQ_REVIEW_ID;
DROP SEQUENCE SEQ_REVIEW_IMAGE_ID;

-- 테이블 작성
CREATE TABLE GRADE (
    GRADE_ID   NUMBER NOT NULL PRIMARY KEY,
    GRADE_NAME VARCHAR2(10) NOT NULL CHECK (GRADE_NAME IN ('PLATINUM', 'GOLD', 'SILVER', 'BRONZE'))
);

CREATE TABLE PAYMENT (
    PAYMENT_ID   NUMBER NOT NULL PRIMARY KEY,
    PAYMENT_NAME VARCHAR2(20) NOT NULL CHECK (PAYMENT_NAME IN ('APPLEPAY', 'KAKAOPAY', 'NAVERPAY', 'HANAPAY', 'PAYCO', 'TOSSPAY', 'VISA', 'MASTERCARD'))
);

CREATE TABLE CATEGORY (
    CATEGORY_ID   NUMBER NOT NULL PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE TAG (
    TAG_ID   NUMBER NOT NULL PRIMARY KEY,
    TAG_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE COUPON (
    COUPON_ID    NUMBER NOT NULL PRIMARY KEY,
    COUPON_NAME  VARCHAR2(50) NOT NULL,
    COUPON_VALUE NUMBER NOT NULL,
    COUPON_TEXT  VARCHAR2(100),
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    DEADLINE     DATE NOT NULL
);

CREATE TABLE PRODUCT_OPTION (
    OPTION_ID    NUMBER NOT NULL PRIMARY KEY,
    OPTION_NAME  VARCHAR2(100) NOT NULL,
    OPTION_PRICE NUMBER NOT NULL CHECK (OPTION_PRICE >= 0)
);

CREATE TABLE MEMBER (
    MEMBER_ID     NUMBER NOT NULL PRIMARY KEY,
    MEMBER_NAME   VARCHAR2(50) NOT NULL CHECK (REGEXP_LIKE(MEMBER_NAME, '^[가-힣a-zA-Z]+$')),
    BIRTH         DATE,
    GENDER        CHAR(1) CHECK (GENDER IN ('M', 'F')),
    LOGIN_ID      VARCHAR2(20) NOT NULL UNIQUE,
    LOGIN_PW      VARCHAR2(100) NOT NULL,
    NICKNAME      VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL         VARCHAR2(100) UNIQUE CHECK (EMAIL IS NULL OR REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    PHONE         VARCHAR2(13) NOT NULL UNIQUE, 
    ROLE          VARCHAR2(10) NOT NULL CHECK (ROLE IN ('USER', 'ADMIN')),
    MEMBER_STATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (MEMBER_STATUS IN (0, 1))
    -- 정상 1 / 탈퇴 0
);

CREATE TABLE WALLET (
    WALLET_ID    NUMBER NOT NULL PRIMARY KEY,
    MEMBER_ID    NUMBER NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    COUPON_ID    NUMBER REFERENCES COUPON(COUPON_ID) ON DELETE CASCADE,
    GRADE_ID     NUMBER NOT NULL REFERENCES GRADE(GRADE_ID) ON DELETE CASCADE,
    TOTAL_AMOUNT NUMBER DEFAULT 0 NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    USED_AT      DATE,
    POINT        NUMBER DEFAULT 0 NOT NULL CHECK (POINT >= 0)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID      NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_TITLE   VARCHAR2(200) NOT NULL,
    PRODUCT_NAME    VARCHAR2(150) NOT NULL,
    PRODUCT_CONTENT VARCHAR2(4000) NOT NULL,
    STOCK           NUMBER NOT NULL CHECK (STOCK >= 0),
    VIEW_COUNT      NUMBER DEFAULT 0 NOT NULL CHECK (VIEW_COUNT >= 0),
    STATUS          VARCHAR2(20) NOT NULL CHECK (STATUS IN ('ON_SALE', 'STOPPED', 'SOLD_OUT', 'HIDDEN'))
);

CREATE TABLE PRODUCT_IMAGE (
    PRODUCT_IMAGE_ID NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_ID       NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    PRODUCT_IMAGE    VARCHAR2(50) NOT NULL,
    IMAGE_TAG        VARCHAR2(50) NOT NULL
);

CREATE TABLE CATEGORY_DETAIL (
    CD_ID       NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_ID  NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CATEGORY_ID NUMBER NOT NULL REFERENCES CATEGORY(CATEGORY_ID) ON DELETE CASCADE
);

CREATE TABLE TAG_DETAIL (
    TD_ID      NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    TAG_ID     NUMBER NOT NULL REFERENCES TAG(TAG_ID) ON DELETE CASCADE
);

CREATE TABLE OPTION_DETAIL (
    PD_ID      NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    OPTION_ID  NUMBER NOT NULL REFERENCES PRODUCT_OPTION(OPTION_ID) ON DELETE CASCADE
);

CREATE TABLE CART (
    CART_ID    NUMBER NOT NULL PRIMARY KEY,
    MEMBER_ID  NUMBER NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    PRODUCT_ID NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    QTY        NUMBER NOT NULL CHECK (QTY > 0)
);

CREATE TABLE WISH (
    WISH_ID    NUMBER NOT NULL PRIMARY KEY,
    MEMBER_ID  NUMBER NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    PRODUCT_ID NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);

CREATE TABLE PRODUCT_ORDER (
    ORDER_ID     NUMBER NOT NULL PRIMARY KEY,
    MEMBER_ID    NUMBER NOT NULL REFERENCES MEMBER(MEMBER_ID),
    PAYMENT_ID   NUMBER NOT NULL REFERENCES PAYMENT(PAYMENT_ID),
    COUPON_ID    NUMBER REFERENCES COUPON(COUPON_ID),
    TOTAL_PRICE  NUMBER NOT NULL CHECK (TOTAL_PRICE >= 0),
    ORDER_STATUS VARCHAR2(20) NOT NULL CHECK (ORDER_STATUS IN ('CART', 'PAYMENT_WAITING', 'PAYMENT_COMPLETED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELED')),
    ORDER_DATE   DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE ORDER_DETAIL (
    OD_ID      NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID),
    ORDER_ID   NUMBER NOT NULL REFERENCES PRODUCT_ORDER(ORDER_ID),
    QTY        NUMBER NOT NULL CHECK (QTY >= 0),
    PRICE_FIX  NUMBER NOT NULL CHECK (PRICE_FIX >= 0)
);

CREATE TABLE DELIVERY (
    DELIVERY_ID     NUMBER NOT NULL PRIMARY KEY,
    ORDER_ID        NUMBER NOT NULL REFERENCES PRODUCT_ORDER(ORDER_ID) ON DELETE CASCADE,
    COMPANY         VARCHAR2(50) NOT NULL,
    TRACKING_NO     VARCHAR2(50) NOT NULL,
    DELIVERY_STATUS VARCHAR2(20) NOT NULL CHECK (DELIVERY_STATUS IN ('PREPARING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELED'))
);

CREATE TABLE REVIEW (
    REVIEW_ID   NUMBER NOT NULL PRIMARY KEY,
    PRODUCT_ID  NUMBER NOT NULL REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    MEMBER_ID   NUMBER NOT NULL REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
    LIKE_COUNT  NUMBER DEFAULT 0 NOT NULL CHECK (LIKE_COUNT >= 0),
    VIEW_COUNT  NUMBER DEFAULT 0 NOT NULL CHECK (VIEW_COUNT >= 0),
    REVIEW_TEXT VARCHAR2(1500) NOT NULL,
    SCORE       NUMBER NOT NULL CHECK (SCORE BETWEEN 1 AND 5),
    WRITE_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IMAGE       VARCHAR2(300)
);

CREATE TABLE REVIEW_IMAGE (
    REVIEW_IMAGE_ID NUMBER NOT NULL PRIMARY KEY,
    REVIEW_ID       NUMBER NOT NULL REFERENCES REVIEW(REVIEW_ID) ON DELETE CASCADE,
    REVIEW_IMAGE    VARCHAR2(50) NOT NULL
);

-- 시퀀스 작성
CREATE SEQUENCE SEQ_GRADE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TAG_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COUPON_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OPTION_ID START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_MEMBER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WALLET_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_IMAGE_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PD_ID START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CART_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WISH_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDER_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_OD_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_IMAGE_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- 더미 데이터 입력

-- 1. COUPON
INSERT INTO COUPON(COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '쿠폰1', 5, '5% 할인 쿠폰', TO_DATE('2026-09-13','YYYY-MM-DD'));
INSERT INTO COUPON(COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '쿠폰2', 10, '10% 할인 쿠폰', TO_DATE('2026-09-15','YYYY-MM-DD'));
INSERT INTO COUPON(COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '쿠폰3', 20, '20% 할인 쿠폰', TO_DATE('2026-09-16','YYYY-MM-DD'));
INSERT INTO COUPON(COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '쿠폰4', 25, '25% 할인 쿠폰', TO_DATE('2026-09-12','YYYY-MM-DD'));

-- 2. TAG
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '1만원대 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '2만원대 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '3만원대 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '5만원대 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '10만원대 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '여성에게 인기 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '남성에게 인기 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '10대에게 인기 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '20대에게 인기 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '30대에게 인기 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '직장 동료용 추천 선물');
INSERT INTO TAG(TAG_ID, TAG_NAME) VALUES (SEQ_TAG_ID.NEXTVAL, '가족용 추천 선물');

-- 3. GRADE
INSERT INTO GRADE(GRADE_ID, GRADE_NAME) VALUES (SEQ_GRADE_ID.NEXTVAL, 'PLATINUM');
INSERT INTO GRADE(GRADE_ID, GRADE_NAME) VALUES (SEQ_GRADE_ID.NEXTVAL, 'GOLD');
INSERT INTO GRADE(GRADE_ID, GRADE_NAME) VALUES (SEQ_GRADE_ID.NEXTVAL, 'SILVER');
INSERT INTO GRADE(GRADE_ID, GRADE_NAME) VALUES (SEQ_GRADE_ID.NEXTVAL, 'BRONZE');

-- 4. MEMBER
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '관리자', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'M', 'test', '1234', '최고관리자', 'gl@gmail.com', '01011110010', 'ADMIN', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '김철수', TO_DATE('1995-03-12', 'YYYY-MM-DD'), 'M', 'test1', '1234', '철수12', 'cs@gmail.com', '01011110001', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '이영희', TO_DATE('1998-07-25', 'YYYY-MM-DD'), 'F', 'test2', '1234', '영희짱', 'yh@gmail.com', '01011110002', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '박민수', TO_DATE('1992-11-05', 'YYYY-MM-DD'), 'M', 'test3', '1234', '민수코딩', 'ms@gmail.com', '01011110003', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '정수진', TO_DATE('2000-01-30', 'YYYY-MM-DD'), 'F', 'test4', '1234', '수진이', 'sj@gmail.com', '01011110004', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '최현우', TO_DATE('1991-08-14', 'YYYY-MM-DD'), 'M', 'test5', '1234', '현우마술', 'hw@gmail.com', '01011110005', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '강다은', TO_DATE('1997-04-18', 'YYYY-MM-DD'), 'F', 'test6', '1234', '다은04', 'de@gmail.com', '01011110006', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '윤지훈', TO_DATE('1994-12-01', 'YYYY-MM-DD'), 'M', 'test7', '1234', '지훈킹', 'jh@gmail.com', '01011110007', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '임서윤', TO_DATE('2002-06-22', 'YYYY-MM-DD'), 'F', 'test8', '1234', '서윤이네', 'sy@gmail.com', '01011110008', 'USER', 1);
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, PHONE, ROLE, MEMBER_STATUS)
VALUES (SEQ_MEMBER_ID.NEXTVAL, '한도현', TO_DATE('1989-09-09', 'YYYY-MM-DD'), 'M', 'test9', '1234', '도현아빠', 'dh@gmail.com', '01011110009', 'USER', 1);

-- 5. PAYMENT
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'APPLEPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'KAKAOPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'NAVERPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'HANAPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'PAYCO');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'TOSSPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'VISA');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'MASTERCARD');

-- 6. WALLET
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 1, 1, 1, 150000, TO_DATE('2026-08-15', 'YYYY-MM-DD'), 3000);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 2, 2, 2, 45000, NULL, 1200);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 3, NULL, 3, 12000, NULL, 500);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 4, 3, 4, 520000, TO_DATE('2026-08-01', 'YYYY-MM-DD'), 10500);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 5, 4, 1, 88000, NULL, 2000);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 6, 1, 2, 5000, TO_DATE('2026-07-20', 'YYYY-MM-DD'), 100);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 7, NULL, 3, 32000, NULL, 800);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 8, 2, 4, 890000, TO_DATE('2026-08-10', 'YYYY-MM-DD'), 25000);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 9, 3, 1, 0, NULL, 0);
INSERT INTO WALLET (WALLET_ID, MEMBER_ID, COUPON_ID, GRADE_ID, TOTAL_AMOUNT, USED_AT, POINT)
VALUES (SEQ_WALLET_ID.NEXTVAL, 10, 4, 2, 210000, TO_DATE('2026-08-18', 'YYYY-MM-DD'), 4500);

-- 7. CATEGORY
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '생일');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '맛있는 선물');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '건강');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '패션·쥬얼리');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '가벼운 선물');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '명품 선물');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '스몰 럭셔리');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '출산·돌');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '결혼·집들이');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '상품권');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '합격·응원');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '재밌는 선물');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '화장품');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '주류');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '육아용품');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '스포츠');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '리빙·키친');

-- 8. PRODUCT
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, STOCK, STATUS)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '코토나 타월 핸드타월 세트', '코토나 타월 핸드타월 세트 선물포장 집들이 선물 200g 펠트바구니, 기프트 세트, 3+2장', '집들이 수건 선물 세트', 100, 'ON_SALE');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, STOCK, STATUS)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '코코도르 그란데 디퓨저 집들이선물', '코코도르 그란데 디퓨저 집들이선물 실내방향제 인테리어 양재동꽃시장, 500ml, 3개', '집들이 방향제 선물', 50, 'ON_SALE');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, STOCK, STATUS)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '김홍도 변색 술잔', '김홍도 변색 술잔 소주잔 맥주잔 4p 세트 변온 위스키 소맥 집들이선물 인생술잔', '술잔 선물 세트', 210, 'ON_SALE');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, STOCK, STATUS)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '내산 한우 1등급 구이용 스테이크 살치살', '내산 한우 1등급 구이용 집들이 홈파티 소고기 스테이크 살치살 100g 냉장', '한우 세트', 22, 'ON_SALE');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, STOCK, STATUS)
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '놋향 방짜유기 수저세트 2인 세트', '놋향 방짜유기 수저세트 2인 모던 유기수저 각인 놋수저 답례품 집들이 선물', '놋향 수저 세트', 95, 'ON_SALE');

-- 9. TAG_DETAIL
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 1, 1);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 1, 6);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 2, 2);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 2, 9);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 2, 12);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 3, 3);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 3, 7);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 4, 4);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 4, 10);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 4, 12);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 5, 5);
INSERT INTO TAG_DETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 5, 11);

-- 10. CATEGORY_DETAIL
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 1, 9);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 1, 17);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 2, 9);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 2, 5);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 3, 14);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 3, 12);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 4, 2);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 5, 9);
INSERT INTO CATEGORY_DETAIL (CD_ID, PRODUCT_ID, CATEGORY_ID) VALUES (SEQ_CD_ID.NEXTVAL, 5, 17);

-- 11. PRODUCT_OPTION
SET DEFINE OFF;       -- sql문에서 &가 들어가면 입력값을 받는데 그거 꺼주는 기능 

INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '코지&펠트바구니', 35800);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '비하인드&펠트바구니', 35800);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '마일드&펠트바구니', 35800);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '에버블루&펠트바구니', 35800);

INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '500ml 2개', 18800);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '500ml 3개', 25800);

INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '옵션 X', 32500);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '인생술잔 쇼핑백 1매', 34500);

INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '살치살 100g', 12900);

INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 모던 수저세트', 37900);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 거북 수저세트', 42900);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 복(福) 수저세트', 42900);
INSERT INTO PRODUCT_OPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 달 수저세트', 42900);

-- 12. OPTION_DETAIL
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 1, 1);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 1, 2);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 1, 3);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 1, 4);

INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 2, 5);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 2, 6);

INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 3, 7);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 3, 8);

INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 4, 9);

INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 5, 10);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 5, 11);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 5, 12);
INSERT INTO OPTION_DETAIL (PD_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_PD_ID.NEXTVAL, 5, 13);

COMMIT;