-- 기존 테이블 / 시퀀스 삭제
DROP TABLE REVIEWHISTORY CASCADE CONSTRAINTS;
DROP TABLE REVIEWLIKE CASCADE CONSTRAINTS;
DROP TABLE REVIEWIMAGE CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE WISH CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE COUPONHISTORY CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE DELIVERYADDRESS CASCADE CONSTRAINTS;
DROP TABLE DELIVERY CASCADE CONSTRAINTS;
DROP TABLE ORDERDETAIL CASCADE CONSTRAINTS;
DROP TABLE PRODUCTORDER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE OPTIONDETAIL CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOPTION CASCADE CONSTRAINTS;
DROP TABLE TAGDETAIL CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE CATEGORYDETAIL CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCTIMAGE CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE POINTHISTORY CASCADE CONSTRAINTS;
DROP TABLE MEMBERPOINT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;



DROP SEQUENCE SEQ_GRADE_ID;
DROP SEQUENCE SEQ_MEMBER_ID;
DROP SEQUENCE SEQ_POINT_ID;
DROP SEQUENCE SEQ_PHIST_ID;
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_PRODUCT_IMAGE_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_CD_ID;
DROP SEQUENCE SEQ_TAG_ID;
DROP SEQUENCE SEQ_TD_ID;
DROP SEQUENCE SEQ_OPTION_ID;
DROP SEQUENCE SEQ_POP_ID;
DROP SEQUENCE SEQ_PAYMENT_ID;
DROP SEQUENCE SEQ_ORDER_ID;
DROP SEQUENCE SEQ_OD_ID;
DROP SEQUENCE SEQ_DELIVERY_ID;
DROP SEQUENCE SEQ_ADD_ID;
DROP SEQUENCE SEQ_COUPON_ID;
DROP SEQUENCE SEQ_CHIST_ID;
DROP SEQUENCE SEQ_CART_ID;
DROP SEQUENCE SEQ_WISH_ID;
DROP SEQUENCE SEQ_REVIEW_ID;
DROP SEQUENCE SEQ_REVIEW_IMAGE_ID;
DROP SEQUENCE SEQ_REVIEW_LIKE_ID;
DROP SEQUENCE SEQ_REVIEW_RHIST_ID;


-- 시퀀스 생성
CREATE SEQUENCE SEQ_GRADE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POINT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PHIST_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_IMAGE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CD_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TAG_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TD_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OPTION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POP_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYMENT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OD_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DELIVERY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ADD_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COUPON_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CHIST_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CART_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_WISH_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_IMAGE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_LIKE_ID START WITH 1 INCREMENT BY 1;


-- 테이블 생성
CREATE TABLE GRADE (
    GRADE_ID NUMBER NOT NULL,
    GRADE_NAME VARCHAR2(10) NOT NULL,
    DISCOUNT_RATE NUMBER NOT NULL,
    MIN_VAL NUMBER NOT NULL,
    MAX_VAL NUMBER NOT NULL,
    
    CONSTRAINT PK_GRADE PRIMARY KEY (GRADE_ID),
    CONSTRAINT CK_GRADE_NAME CHECK (GRADE_NAME IN ('PLATINUM', 'GOLD', 'SILVER', 'BRONZE'))
);

CREATE TABLE MEMBER (
    MEMBER_ID NUMBER NOT NULL,
    GRADE_ID NUMBER DEFAULT 1,
    TOTAL_AMOUNT NUMBER DEFAULT 0,
    MEMBER_NAME VARCHAR2(50) NOT NULL,
    BIRTH DATE,
    GENDER CHAR(1),
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PW VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(13) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'USER' NOT NULL,
    MEMBER_STATUS NUMBER DEFAULT 1 NOT NULL,
    
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_MEMBER_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_MEMBER_PHONE UNIQUE (PHONE),
    CONSTRAINT CK_MEMBER_GENDER CHECK (GENDER IN ('M', 'm', 'F', 'f')),
    CONSTRAINT CK_MEMBER_ROLE CHECK (ROLE IN ('USER', 'ADMIN')),
    CONSTRAINT CK_MEMBER_STATUS CHECK (MEMBER_STATUS IN(0, 1)),
    CONSTRAINT FK_MEMBER_GRADE FOREIGN KEY (GRADE_ID) REFERENCES GRADE (GRADE_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_TITLE VARCHAR2(200) NOT NULL,
    PRODUCT_NAME VARCHAR2(150) NOT NULL,
    PRODUCT_CONTENT VARCHAR2(4000) NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT CK_PRODUCT_VIEW_COUNT CHECK (VIEW_COUNT >= 0),
    CONSTRAINT CK_PRODUCT_STATUS CHECK (STATUS IN ('ON_SALE', 'STOPPED', 'SOLD_OUT', 'HIDDEN'))
);

CREATE TABLE PRODUCTIMAGE (
    PRODUCT_IMAGE_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_IMAGE_ORIGINAL_NAME VARCHAR2(300) NOT NULL,
    PRODUCT_IMAGE_SAVE_NAME VARCHAR2(300) NOT NULL,
    PRODUCT_IMAGE_PATH VARCHAR2(300) NOT NULL,
    PRODUCT_TITLE_IMAGE NUMBER NOT NULL,
    PRODUCT_IMAGE_CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_PRODUCT_IMAGE PRIMARY KEY (PRODUCT_IMAGE_ID),
    CONSTRAINT FK_PRODUCT_IMAGE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT CK_PTITLE_IMAGE CHECK (PRODUCT_TITLE_IMAGE IN (0,1,2))
);

CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER NOT NULL,
    CATEGORY_NAME VARCHAR2(50) NOT NULL,
    
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE CATEGORYDETAIL (
    CD_ID NUMBER NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    
    CONSTRAINT PK_CATEGORY_DETAIL PRIMARY KEY (CD_ID),
    CONSTRAINT UK_CATEGORY_DETAIL UNIQUE (CATEGORY_ID, PRODUCT_ID),
    CONSTRAINT FK_CD_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID),
    CONSTRAINT FK_CD_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE
);

CREATE TABLE TAG (
    TAG_ID NUMBER NOT NULL,
    TAG_NAME VARCHAR2(50) NOT NULL,
    TAG_COLOR VARCHAR2(7) NOT NULL,
    
    CONSTRAINT PK_TAG PRIMARY KEY (TAG_ID)
);

CREATE TABLE TAGDETAIL (
    TD_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    TAG_ID NUMBER NOT NULL,
    
    CONSTRAINT PK_TAG_DETAIL PRIMARY KEY (TD_ID),
    CONSTRAINT UK_TAG_DETAIL UNIQUE (PRODUCT_ID, TAG_ID),
    CONSTRAINT FK_TD_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TD_TAG FOREIGN KEY (TAG_ID) REFERENCES TAG (TAG_ID)
);

CREATE TABLE PRODUCTOPTION (
    OPTION_ID NUMBER NOT NULL,
    OPTION_NAME VARCHAR2(100) NOT NULL,
    OPTION_PRICE NUMBER NOT NULL,
    OPTION_STOCK NUMBER NOT NULL,
    
    CONSTRAINT PK_PRODUCT_OPTION PRIMARY KEY (OPTION_ID),
    CONSTRAINT CK_PRODUCT_STOCK CHECK (OPTION_STOCK >= 0)
);

CREATE TABLE OPTIONDETAIL (
    POP_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    OPTION_ID NUMBER NOT NULL,
    
    CONSTRAINT PK_OPTION_DETAIL PRIMARY KEY (POP_ID),
    CONSTRAINT UK_OPTION_DETAIL UNIQUE (PRODUCT_ID, OPTION_ID),
    CONSTRAINT FK_OD_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OD_OPTION FOREIGN KEY (OPTION_ID) REFERENCES PRODUCTOPTION (OPTION_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER NOT NULL,
    PAYMENT_NAME VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT CK_PAYMENT_NAME CHECK (PAYMENT_NAME IN ('APPLEPAY', 'KAKAOPAY', 'NAVERPAY', 'HANAPAY', 'PAYCO', 'TOSSPAY', 'VISA', 'MASTERCARD'))
);

CREATE TABLE PRODUCTORDER (
    ORDER_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    TOTAL_PRICE NUMBER,
    ORDER_STATUS VARCHAR2(20),
    ORDER_DATE DATE DEFAULT SYSDATE,
    USED_POINT NUMBER DEFAULT 0 NOT NULL,
    PAYMENT_ID NUMBER NOT NULL,
    ADDRESS_NAME_FIX VARCHAR2(50) NOT NULL,
    DETAIL_ADDRESS_FIX VARCHAR2(200) NOT NULL,
      
    CONSTRAINT PK_PRODUCT_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT CK_ORDER_TOTAL_PRICE CHECK (TOTAL_PRICE >= 0),
    CONSTRAINT CK_ORDER_STATUS CHECK (ORDER_STATUS IN ('CART', 'PAYMENT_WAITING', 'PAYMENT_COMPLETED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELED')),
    CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_ORDER_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
);

CREATE TABLE ORDERDETAIL (
    OD_ID NUMBER NOT NULL,
    ORDER_ID NUMBER NOT NULL,
    POP_ID NUMBER NOT NULL,
    QTY NUMBER,
    PRICE_FIX NUMBER,
    GRADE_DIS_AMOUNT NUMBER,

    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (OD_ID),
    CONSTRAINT UK_ORDER_DETAIL UNIQUE (ORDER_ID, POP_ID),
    CONSTRAINT CK_OD_QTY CHECK (QTY >= 0),
    CONSTRAINT CK_OD_PRICE_FIX CHECK (PRICE_FIX >= 0),
    CONSTRAINT CK_OD_DIS_AMOUNT CHECK (GRADE_DIS_AMOUNT >= 0),
    CONSTRAINT FK_OD_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTORDER (ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OD_POP FOREIGN KEY (POP_ID) REFERENCES OPTIONDETAIL (POP_ID)
);

CREATE TABLE DELIVERY (
    DELIVERY_ID NUMBER NOT NULL,
    ORDER_ID NUMBER NOT NULL,
    COMPANY VARCHAR2(50),
    TRACKING_NO VARCHAR2(50),
    DELIVERY_STATUS VARCHAR2(20),
    
    CONSTRAINT PK_DELIVERY PRIMARY KEY (DELIVERY_ID),
    CONSTRAINT CK_DELIVERY_STATUS CHECK (DELIVERY_STATUS IN ('PREPARING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELED')),
    CONSTRAINT FK_DELIVERY_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTORDER (ORDER_ID) ON DELETE CASCADE
);

CREATE TABLE DELIVERYADDRESS (
    ADD_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    ADDRESS_NAME VARCHAR2(50) NOT NULL,
    DETAIL_ADDRESS VARCHAR2(200) NOT NULL,
    IS_DEFAULT CHAR(1),
    
    CONSTRAINT PK_DELIVERY_ADDRESS PRIMARY KEY (ADD_ID),
    CONSTRAINT CK_ADD_IS_DEFAULT CHECK (IS_DEFAULT IN ('Y', 'y', 'N', 'n')),
    CONSTRAINT FK_ADD_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

-- 회원당 기본 배송지 ('Y') 1개만 허용하는 조건부 유니크 인덱스 (Y일 때만 인덱스 검증)
CREATE UNIQUE INDEX UX_DELIVERYADDRESS_IS_DEFAULT 
ON DELIVERYADDRESS (
    CASE WHEN UPPER(IS_DEFAULT) = 'Y' THEN MEMBER_ID ELSE NULL END
);

CREATE TABLE MEMBERPOINT (
    POINT_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    POINT NUMBER DEFAULT 0 NOT NULL,
    
    CONSTRAINT PK_MEMBER_POINT PRIMARY KEY (POINT_ID),
    CONSTRAINT UK_MEMBER_POINT_MEMBER UNIQUE (MEMBER_ID),
    CONSTRAINT FK_MEMBER_POINT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);

CREATE TABLE POINTHISTORY (
    PHIST_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    ORDER_ID NUMBER,
    TYPE VARCHAR2(10) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    BALANCE NUMBER NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    
    CONSTRAINT PK_POINT_HISTORY PRIMARY KEY (PHIST_ID),
    CONSTRAINT CK_PHIST_TYPE CHECK (TYPE IN ('EARN', 'USE', 'CANCELED')),
    CONSTRAINT FK_PHIST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_PHIST_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTORDER (ORDER_ID)
);

CREATE TABLE COUPON (
    COUPON_ID NUMBER NOT NULL,
    COUPON_NAME VARCHAR2(50) NOT NULL,
    COUPON_VALUE NUMBER NOT NULL,
    COUPON_TEXT VARCHAR2(300),
    CREATED_AT DATE DEFAULT SYSDATE,
    DEADLINE DATE NOT NULL,
    
    CONSTRAINT PK_COUPON PRIMARY KEY (COUPON_ID)
);

CREATE TABLE COUPONHISTORY (
    CHIST_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    COUPON_ID NUMBER NOT NULL,
    ORDER_ID NUMBER,
    TYPE VARCHAR2(10) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_COUPON_HISTORY PRIMARY KEY (CHIST_ID),
    CONSTRAINT CK_CHIST_TYPE CHECK (TYPE IN ('ISSUE', 'USE', 'EXPIRE', 'CANCELED')),
    CONSTRAINT FK_CHIST_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_CHIST_COUPON FOREIGN KEY (COUPON_ID) REFERENCES COUPON (COUPON_ID),
    CONSTRAINT FK_CHIST_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTORDER (ORDER_ID)
);

CREATE TABLE CART (
    CART_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    POP_ID NUMBER NOT NULL,
    QTY NUMBER DEFAULT 1,
    
    CONSTRAINT PK_CART PRIMARY KEY (CART_ID),
    CONSTRAINT UK_CART UNIQUE (MEMBER_ID, POP_ID),
    CONSTRAINT CK_CART_QTY CHECK (QTY >= 0),
    CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_POP FOREIGN KEY (POP_ID) REFERENCES OPTIONDETAIL (POP_ID)
);

CREATE TABLE WISH (
    WISH_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    
    CONSTRAINT PK_WISH PRIMARY KEY (WISH_ID),
    CONSTRAINT UK_WISH UNIQUE (MEMBER_ID, PRODUCT_ID),
    CONSTRAINT FK_WISH_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_WISH_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW (
    REVIEW_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    OD_ID NUMBER NOT NULL,
    REVIEW_STATUS NUMBER DEFAULT 1 NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0,
    REVIEW_TEXT VARCHAR2(1500),
    SCORE NUMBER NOT NULL,
    WRITE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT UK_REVIEW UNIQUE (MEMBER_ID, OD_ID),
    CONSTRAINT CK_REVIEW_STATUS CHECK (REVIEW_STATUS IN(0, 1)),
    CONSTRAINT CK_REVIEW_VIEW CHECK (VIEW_COUNT >= 0),
    CONSTRAINT CK_REVIEW_SCORE CHECK (SCORE BETWEEN 1 AND 5),
    CONSTRAINT FK_REVIEW_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_REVIEW_OD FOREIGN KEY (OD_ID) REFERENCES ORDERDETAIL (OD_ID)
);

CREATE TABLE REVIEWIMAGE (
    REVIEW_IMAGE_ID NUMBER NOT NULL,
    REVIEW_ID NUMBER NOT NULL,
    REVIEW_IMAGE_ORIGINAL_NAME VARCHAR2(300) NOT NULL,
    REVIEW_IMAGE_SAVE_NAME VARCHAR2(300) NOT NULL,
    REVIEW_IMAGE_PATH VARCHAR2(300) NOT NULL,
    REVIEW_TITLE_IMAGE NUMBER NOT NULL,
    REVIEW_IMAGE_CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PK_REVIEW_IMAGE PRIMARY KEY (REVIEW_IMAGE_ID),
    CONSTRAINT FK_RIMAGE_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE,
    CONSTRAINT CK_RTITLE_IMAGE CHECK (REVIEW_TITLE_IMAGE IN (0,1))
);

CREATE TABLE REVIEWLIKE (
    LIKE_ID NUMBER NOT NULL,
    REVIEW_ID NUMBER NOT NULL,
    MEMBER_ID NUMBER NOT NULL,
    
    CONSTRAINT PK_REVIEWLIKE_ID PRIMARY KEY (LIKE_ID),
    CONSTRAINT UK_REVIEWLIKE UNIQUE (REVIEW_ID, MEMBER_ID),
    CONSTRAINT FK_LIKE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIKE_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE
);


-- DEFINE OFF: 문자열 내 '&' 기호가 들어갈 때 변수 입력창이 뜨는 것을 방지
SET DEFINE OFF;

--------------------------------------------------
-- 1. GRADE (회원 등급)
--------------------------------------------------
INSERT INTO GRADE (GRADE_ID, GRADE_NAME, DISCOUNT_RATE, MIN_VAL, MAX_VAL) 
VALUES (SEQ_GRADE_ID.NEXTVAL, 'BRONZE', 0.02, 0, 99999);
INSERT INTO GRADE (GRADE_ID, GRADE_NAME, DISCOUNT_RATE, MIN_VAL, MAX_VAL) 
VALUES (SEQ_GRADE_ID.NEXTVAL, 'SILVER', 0.05, 100000, 499999);
INSERT INTO GRADE (GRADE_ID, GRADE_NAME, DISCOUNT_RATE, MIN_VAL, MAX_VAL) 
VALUES (SEQ_GRADE_ID.NEXTVAL, 'GOLD', 0.10, 500000, 999999);
INSERT INTO GRADE (GRADE_ID, GRADE_NAME, DISCOUNT_RATE, MIN_VAL, MAX_VAL) 
VALUES (SEQ_GRADE_ID.NEXTVAL, 'PLATINUM', 0.15, 1000000, 99999999);

--------------------------------------------------
-- 2. MEMBER (회원)
--------------------------------------------------
INSERT INTO MEMBER (MEMBER_ID, GRADE_ID, TOTAL_AMOUNT, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, CREATED_AT, PHONE, ROLE, MEMBER_STATUS) 
VALUES (SEQ_MEMBER_ID.NEXTVAL, 1, 0, '관리자', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'M', 'admin', '$2a$10$9xqG6JYscfoXl47UMOmseOZDg5F9FX0lDIRQ9x4Rl/C5hzeeYWx8i', '어드민', 'admin@tuna.com', SYSDATE, '010-0000-0000', 'ADMIN', 1);

INSERT INTO MEMBER (MEMBER_ID, GRADE_ID, TOTAL_AMOUNT, MEMBER_NAME, BIRTH, GENDER, LOGIN_ID, LOGIN_PW, NICKNAME, EMAIL, CREATED_AT, PHONE, ROLE, MEMBER_STATUS) 
VALUES (SEQ_MEMBER_ID.NEXTVAL, 1, 0, '홍길동', TO_DATE('1995-05-15', 'YYYY-MM-DD'), 'M', 'user01', '$2a$10$9xqG6JYscfoXl47UMOmseOZDg5F9FX0lDIRQ9x4Rl/C5hzeeYWx8i', '길동이', 'user01@tuna.com', SYSDATE, '010-1234-5678', 'USER', 1);

--------------------------------------------------
-- 3. MEMBERPOINT & POINTHISTORY (포인트)
--------------------------------------------------
INSERT INTO MEMBERPOINT (POINT_ID, MEMBER_ID, POINT) VALUES (SEQ_POINT_ID.NEXTVAL, 1, 10000);
INSERT INTO MEMBERPOINT (POINT_ID, MEMBER_ID, POINT) VALUES (SEQ_POINT_ID.NEXTVAL, 2, 3000);

INSERT INTO POINTHISTORY (PHIST_ID, MEMBER_ID, ORDER_ID, TYPE, AMOUNT, BALANCE, CREATED_AT) 
VALUES (SEQ_PHIST_ID.NEXTVAL, 2, NULL, 'EARN', 3000, 3000, SYSDATE);

--------------------------------------------------
-- 4. DELIVERYADDRESS (배송지)
--------------------------------------------------
INSERT INTO DELIVERYADDRESS (ADD_ID, MEMBER_ID, ADDRESS_NAME, DETAIL_ADDRESS, IS_DEFAULT) 
VALUES (SEQ_ADD_ID.NEXTVAL, 2, '우리집', '서울특별시 강남구 테헤란로 123 4층', 'Y');

--------------------------------------------------
-- 5. PRODUCT (상품)
--------------------------------------------------
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, VIEW_COUNT, STATUS) 
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '코토나 타월 핸드타월 세트', '코토나 타월 핸드타월 세트', '집들이 수건 선물 세트', 0, 'ON_SALE'); -- PRODUCT_ID: 1

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, VIEW_COUNT, STATUS) 
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '코코도르 그란데 디퓨저 집들이선물', '코코도르 그란데 디퓨저', '집들이 방향제 선물', 0, 'ON_SALE'); -- PRODUCT_ID: 2

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, VIEW_COUNT, STATUS) 
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '김홍도 변색 술잔', '김홍도 변색 술잔 4p 세트', '술잔 선물 세트', 0, 'ON_SALE'); -- PRODUCT_ID: 3

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, VIEW_COUNT, STATUS) 
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '내산 한우 1등급 구이용 스테이크 살치살', '내산 한우 1등급 살치살 100g', '한우 세트', 0, 'ON_SALE'); -- PRODUCT_ID: 4

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_TITLE, PRODUCT_NAME, PRODUCT_CONTENT, VIEW_COUNT, STATUS) 
VALUES (SEQ_PRODUCT_ID.NEXTVAL, '놋향 방짜유기 수저세트 2인 세트', '놋향 방짜유기 수저세트', '놋향 수저 세트', 0, 'ON_SALE'); -- PRODUCT_ID: 5

--------------------------------------------------
-- 6. PRODUCTIMAGE (상품 이미지)
--------------------------------------------------
INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT) 
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 1, 'tuna_main.jpg', 'uuid_tuna_main.jpg', '/upload/product/', 1, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 1, 'towel_main.jpg', 'uuid_towel_main.jpg', '/upload/product/', 0, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 1, 'towel_detail1.jpg', 'uuid_towel_detail1.jpg', '/upload/product/', 1, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 1, 'towel_detail2.jpg', 'uuid_towel_detail2.jpg', '/upload/product/', 2, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 2, 'diffuser_main.png', 'uuid_diffuser_main.png', '/upload/product/', 0, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 2, 'diffuser_info.png', 'uuid_diffuser_info.png', '/upload/product/', 1, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 3, 'glass_main.jpg', 'uuid_glass_main.jpg', '/upload/product/', 0, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 3, 'glass_sub1.jpg', 'uuid_glass_sub1.jpg', '/upload/product/', 1, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 3, 'glass_sub2.jpg', 'uuid_glass_sub2.jpg', '/upload/product/', 2, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 4, 'beef_main.jpg', 'uuid_beef_main.jpg', '/upload/product/', 0, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 4, 'beef_detail.jpg', 'uuid_beef_detail.jpg', '/upload/product/', 1, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 5, 'sujeo_main.jpg', 'uuid_sujeo_main.jpg', '/upload/product/', 0, SYSDATE);

INSERT INTO PRODUCTIMAGE (PRODUCT_IMAGE_ID, PRODUCT_ID, PRODUCT_IMAGE_ORIGINAL_NAME, PRODUCT_IMAGE_SAVE_NAME, PRODUCT_IMAGE_PATH, PRODUCT_TITLE_IMAGE, PRODUCT_IMAGE_CREATE_AT)
VALUES (SEQ_PRODUCT_IMAGE_ID.NEXTVAL, 5, 'sujeo_photo.jpg', 'uuid_sujeo_photo.jpg', '/upload/product/', 2, SYSDATE);

--------------------------------------------------
-- 7. CATEGORY & CATEGORYDETAIL (카테고리)
--------------------------------------------------
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '생일');          -- 1
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '맛있는 선물');   -- 2
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '건강');          -- 3
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '결혼·집들이');   -- 4
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '주류');          -- 5
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (SEQ_CATEGORY_ID.NEXTVAL, '리빙·키친');     -- 6

INSERT INTO CATEGORYDETAIL (CD_ID, CATEGORY_ID, PRODUCT_ID) VALUES (SEQ_CD_ID.NEXTVAL, 4, 1);
INSERT INTO CATEGORYDETAIL (CD_ID, CATEGORY_ID, PRODUCT_ID) VALUES (SEQ_CD_ID.NEXTVAL, 6, 1);
INSERT INTO CATEGORYDETAIL (CD_ID, CATEGORY_ID, PRODUCT_ID) VALUES (SEQ_CD_ID.NEXTVAL, 4, 2);
INSERT INTO CATEGORYDETAIL (CD_ID, CATEGORY_ID, PRODUCT_ID) VALUES (SEQ_CD_ID.NEXTVAL, 5, 3);
INSERT INTO CATEGORYDETAIL (CD_ID, CATEGORY_ID, PRODUCT_ID) VALUES (SEQ_CD_ID.NEXTVAL, 2, 4);
INSERT INTO CATEGORYDETAIL (CD_ID, CATEGORY_ID, PRODUCT_ID) VALUES (SEQ_CD_ID.NEXTVAL, 4, 5);

--------------------------------------------------
-- 8. TAG & TAGDETAIL (태그)
--------------------------------------------------
INSERT INTO TAG (TAG_ID, TAG_NAME, TAG_COLOR) VALUES (SEQ_TAG_ID.NEXTVAL, '1만원대 선물', '#FFD1DC');        -- 1
INSERT INTO TAG (TAG_ID, TAG_NAME, TAG_COLOR) VALUES (SEQ_TAG_ID.NEXTVAL, '2만원대 선물', '#FFE5CC');        -- 2
INSERT INTO TAG (TAG_ID, TAG_NAME, TAG_COLOR) VALUES (SEQ_TAG_ID.NEXTVAL, '3만원대 선물', '#D0F0C0');        -- 3
INSERT INTO TAG (TAG_ID, TAG_NAME, TAG_COLOR) VALUES (SEQ_TAG_ID.NEXTVAL, '5만원대 선물', '#D4E6F1');        -- 4
INSERT INTO TAG (TAG_ID, TAG_NAME, TAG_COLOR) VALUES (SEQ_TAG_ID.NEXTVAL, '20대에게 인기 선물', '#E8DAEF');   -- 5

INSERT INTO TAGDETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 1, 3);
INSERT INTO TAGDETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 2, 2);
INSERT INTO TAGDETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 3, 3);
INSERT INTO TAGDETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 4, 1);
INSERT INTO TAGDETAIL (TD_ID, PRODUCT_ID, TAG_ID) VALUES (SEQ_TD_ID.NEXTVAL, 5, 3);

--------------------------------------------------
-- 9. PRODUCTOPTION (상품 옵션 목록)
--------------------------------------------------
-- 타월 세트 옵션 (OPTION_ID: 1 ~ 4)
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '코지&펠트바구니', 35800, 100);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '비하인드&펠트바구니', 35800, 100);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '마일드&펠트바구니', 35800, 100);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '에버블루&펠트바구니', 35800, 100);

-- 디퓨저 옵션 (OPTION_ID: 5 ~ 6)
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '500ml 2개', 18800, 150);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '500ml 3개', 25800, 150);

-- 술잔 옵션 (OPTION_ID: 7 ~ 8)
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '옵션 X', 32500, 200);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '인생술잔 쇼핑백 1매', 34500, 200);

-- 살치살 옵션 (OPTION_ID: 9)
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '살치살 100g', 12900, 50);

-- 수저 세트 옵션 (OPTION_ID: 10 ~ 13)
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 모던 수저세트', 37900, 80);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 거북 수저세트', 42900, 80);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 복(福) 수저세트', 42900, 80);
INSERT INTO PRODUCTOPTION (OPTION_ID, OPTION_NAME, OPTION_PRICE, OPTION_STOCK) VALUES (SEQ_OPTION_ID.NEXTVAL, '2인 달 수저세트', 42900, 80);

--------------------------------------------------
-- 10. OPTIONDETAIL (상품-옵션 매핑)
--------------------------------------------------
-- PRODUCT 1 (타월 세트)
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 1, 1); -- POP_ID: 1
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 1, 2); -- POP_ID: 2
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 1, 3); -- POP_ID: 3
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 1, 4); -- POP_ID: 4

-- PRODUCT 2 (디퓨저)
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 2, 5); -- POP_ID: 5
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 2, 6); -- POP_ID: 6

-- PRODUCT 3 (술잔)
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 3, 7); -- POP_ID: 7
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 3, 8); -- POP_ID: 8

-- PRODUCT 4 (살치살)
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 4, 9); -- POP_ID: 9

-- PRODUCT 5 (수저 세트)
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 5, 10); -- POP_ID: 10
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 5, 11); -- POP_ID: 11
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 5, 12); -- POP_ID: 12
INSERT INTO OPTIONDETAIL (POP_ID, PRODUCT_ID, OPTION_ID) VALUES (SEQ_POP_ID.NEXTVAL, 5, 13); -- POP_ID: 13

--------------------------------------------------
-- 11. PAYMENT (결제 수단)
--------------------------------------------------
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'KAKAOPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'NAVERPAY');
INSERT INTO PAYMENT (PAYMENT_ID, PAYMENT_NAME) VALUES (SEQ_PAYMENT_ID.NEXTVAL, 'MASTERCARD');

--------------------------------------------------
-- 12. COUPON & COUPONHISTORY (쿠폰)
--------------------------------------------------
INSERT INTO COUPON (COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, CREATED_AT, DEADLINE) 
VALUES (SEQ_COUPON_ID.NEXTVAL, '신규가입 10% 할인 쿠폰', 0.10, '첫 구매 시 사용 가능', SYSDATE, SYSDATE + 30);

INSERT INTO COUPON (COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, CREATED_AT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '첫 구매 감사 10% 쿠폰', 0.10, '첫 주문 완료 후 재구매 시 사용 가능', SYSDATE, ADD_MONTHS(SYSDATE, 2));

INSERT INTO COUPON (COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, CREATED_AT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '주말 특가 15% 할인 쿠폰', 0.15, '주말 주문 건에 한해 적용 가능', SYSDATE, SYSDATE + 7);

INSERT INTO COUPON (COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, CREATED_AT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, 'VIP 전용 특별 쿠폰', 0.20, 'VIP 등급 이상 회원만 사용 가능', SYSDATE, ADD_MONTHS(SYSDATE, 6));

INSERT INTO COUPON (COUPON_ID, COUPON_NAME, COUPON_VALUE, COUPON_TEXT, CREATED_AT, DEADLINE)
VALUES (SEQ_COUPON_ID.NEXTVAL, '시즌 OFF 30% 슈퍼 할인', 0.30, '시즌 Off 지정 상품 구매 시 적용 가능', SYSDATE, SYSDATE + 14);

INSERT INTO COUPONHISTORY (CHIST_ID, MEMBER_ID, COUPON_ID, ORDER_ID, TYPE, CREATED_AT) 
VALUES (SEQ_CHIST_ID.NEXTVAL, 2, 1, NULL, 'ISSUE', SYSDATE);

INSERT INTO COUPONHISTORY (CHIST_ID, MEMBER_ID, COUPON_ID, ORDER_ID, TYPE, CREATED_AT)
VALUES (SEQ_CHIST_ID.NEXTVAL, 2, 2, NULL, 'ISSUE', SYSDATE - 5);

INSERT INTO COUPONHISTORY (CHIST_ID, MEMBER_ID, COUPON_ID, ORDER_ID, TYPE, CREATED_AT)
VALUES (SEQ_CHIST_ID.NEXTVAL, 2, 3, NULL, 'ISSUE', SYSDATE - 3);

INSERT INTO COUPONHISTORY (CHIST_ID, MEMBER_ID, COUPON_ID, ORDER_ID, TYPE, CREATED_AT)
VALUES (SEQ_CHIST_ID.NEXTVAL, 2, 4, NULL, 'ISSUE', SYSDATE - 1);

INSERT INTO COUPONHISTORY (CHIST_ID, MEMBER_ID, COUPON_ID, ORDER_ID, TYPE, CREATED_AT)
VALUES (SEQ_CHIST_ID.NEXTVAL, 2, 5, NULL, 'ISSUE', SYSDATE);

--------------------------------------------------
-- 13. CART & WISH (장바구니/찜)
--------------------------------------------------
INSERT INTO CART (CART_ID, MEMBER_ID, POP_ID, QTY) VALUES (SEQ_CART_ID.NEXTVAL, 2, 1, 2);

INSERT INTO CART (CART_ID, MEMBER_ID, POP_ID, QTY)
VALUES (SEQ_CART_ID.NEXTVAL, 2, 2, 2);

INSERT INTO CART (CART_ID, MEMBER_ID, POP_ID, QTY)
VALUES (SEQ_CART_ID.NEXTVAL, 2, 3, 1);

INSERT INTO CART (CART_ID, MEMBER_ID, POP_ID, QTY)
VALUES (SEQ_CART_ID.NEXTVAL, 2, 5, 3);

INSERT INTO WISH (WISH_ID, MEMBER_ID, PRODUCT_ID) VALUES (SEQ_WISH_ID.NEXTVAL, 2, 1);

INSERT INTO WISH (WISH_ID, MEMBER_ID, PRODUCT_ID)
VALUES (SEQ_WISH_ID.NEXTVAL, 2, 4);

INSERT INTO WISH (WISH_ID, MEMBER_ID, PRODUCT_ID)
VALUES (SEQ_WISH_ID.NEXTVAL, 2, 2);

INSERT INTO WISH (WISH_ID, MEMBER_ID, PRODUCT_ID)
VALUES (SEQ_WISH_ID.NEXTVAL, 2, 3);

INSERT INTO WISH (WISH_ID, MEMBER_ID, PRODUCT_ID)
VALUES (SEQ_WISH_ID.NEXTVAL, 2, 5);


--------------------------------------------------
-- 14. PRODUCTORDER & ORDERDETAIL (주문/주문상세)
--------------------------------------------------
INSERT INTO PRODUCTORDER (ORDER_ID, MEMBER_ID, TOTAL_PRICE, ORDER_STATUS, ORDER_DATE, USED_POINT, PAYMENT_ID, ADDRESS_NAME_FIX, DETAIL_ADDRESS_FIX) 
VALUES (SEQ_ORDER_ID.NEXTVAL, 2, 71600, 'PAYMENT_COMPLETED', SYSDATE, 0, 1, '우리집', '서울특별시 강남구 테헤란로 123 4층'); -- ORDER_ID: 1

INSERT INTO PRODUCTORDER (
ORDER_ID, MEMBER_ID, TOTAL_PRICE, ORDER_STATUS, ORDER_DATE, 
USED_POINT, PAYMENT_ID, ADDRESS_NAME_FIX, DETAIL_ADDRESS_FIX
) VALUES (
SEQ_ORDER_ID.NEXTVAL, 2, 58000, 'DELIVERED', SYSDATE - 1, 
1000, 1, '홍길동', '서울시 마포구 월드컵북로 21, 3층'
);

INSERT INTO PRODUCTORDER (
ORDER_ID, MEMBER_ID, TOTAL_PRICE, ORDER_STATUS, ORDER_DATE, 
USED_POINT, PAYMENT_ID, ADDRESS_NAME_FIX, DETAIL_ADDRESS_FIX
) VALUES (
SEQ_ORDER_ID.NEXTVAL, 2, 18800, 'SHIPPED', SYSDATE - 3, 
0, 1, '홍길동', '서울시 마포구 월드컵북로 21, 3층'
);

INSERT INTO PRODUCTORDER (
ORDER_ID, MEMBER_ID, TOTAL_PRICE, ORDER_STATUS, ORDER_DATE, 
USED_POINT, PAYMENT_ID, ADDRESS_NAME_FIX, DETAIL_ADDRESS_FIX
) VALUES (
SEQ_ORDER_ID.NEXTVAL, 2, 102300, 'PREPARING', SYSDATE - 5, 
5000, 1, '홍길동', '서울시 마포구 월드컵북로 21, 3층'
);

INSERT INTO PRODUCTORDER (
ORDER_ID, MEMBER_ID, TOTAL_PRICE, ORDER_STATUS, ORDER_DATE, 
USED_POINT, PAYMENT_ID, ADDRESS_NAME_FIX, DETAIL_ADDRESS_FIX
) VALUES (
SEQ_ORDER_ID.NEXTVAL, 2, 29000, 'CANCELED', SYSDATE - 10, 
0, 1, '홍길동', '서울시 마포구 월드컵북로 21, 3층'
);


INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT) 
VALUES (SEQ_OD_ID.NEXTVAL, 1, 1, 2, 35800, 0);

INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT)
VALUES (SEQ_OD_ID.NEXTVAL, 2, 1, 2, 29000, 0);

INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT)
VALUES (SEQ_OD_ID.NEXTVAL, 3, 5, 1, 18800, 0);

INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT)
VALUES (SEQ_OD_ID.NEXTVAL, 4, 7, 1, 32500, 1000);

INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT)
VALUES (SEQ_OD_ID.NEXTVAL, 4, 10, 2, 37900, 0);

INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT)
VALUES (SEQ_OD_ID.NEXTVAL, 5, 2, 1, 29000, 0);


--------------------------------------------------
-- 15. DELIVERY (배송)
--------------------------------------------------
INSERT INTO DELIVERY (DELIVERY_ID, ORDER_ID, COMPANY, TRACKING_NO, DELIVERY_STATUS) 
VALUES (SEQ_DELIVERY_ID.NEXTVAL, 1, 'CJ대한통운', '1234567890', 'PREPARING');

INSERT INTO DELIVERY (DELIVERY_ID, ORDER_ID, COMPANY, TRACKING_NO, DELIVERY_STATUS)
VALUES (SEQ_DELIVERY_ID.NEXTVAL, 2, 'CJ대한통운', '123456789012', 'DELIVERED');

INSERT INTO DELIVERY (DELIVERY_ID, ORDER_ID, COMPANY, TRACKING_NO, DELIVERY_STATUS)
VALUES (SEQ_DELIVERY_ID.NEXTVAL, 3, '우체국택배', '987654321098', 'SHIPPED');

INSERT INTO DELIVERY (DELIVERY_ID, ORDER_ID, COMPANY, TRACKING_NO, DELIVERY_STATUS)
VALUES (SEQ_DELIVERY_ID.NEXTVAL, 4, NULL, NULL, 'PREPARING');

INSERT INTO DELIVERY (DELIVERY_ID, ORDER_ID, COMPANY, TRACKING_NO, DELIVERY_STATUS)
VALUES (SEQ_DELIVERY_ID.NEXTVAL, 5, NULL, NULL, 'CANCELED');


--------------------------------------------------
-- 16. REVIEW & REVIEWIMAGE (리뷰)
--------------------------------------------------
INSERT INTO REVIEW (REVIEW_ID, MEMBER_ID, OD_ID, REVIEW_STATUS, VIEW_COUNT, REVIEW_TEXT, SCORE, WRITE_DATE) 
VALUES (SEQ_REVIEW_ID.NEXTVAL, 2, 1, 1, 1, '배송도 빠르고 수건 감촉이 너무 좋아요!', 5, SYSTIMESTAMP);

INSERT INTO REVIEW (
REVIEW_ID, MEMBER_ID, OD_ID, REVIEW_STATUS, VIEW_COUNT, 
REVIEW_TEXT, SCORE, WRITE_DATE
) VALUES (
SEQ_REVIEW_ID.NEXTVAL, 2, 2, 1, 20, 
'배송도 엄청 빠르고 품질이 너무 좋습니다! 강추합니다.', 5, SYSTIMESTAMP - INTERVAL '2' DAY
);

INSERT INTO REVIEW (
REVIEW_ID, MEMBER_ID, OD_ID, REVIEW_STATUS, VIEW_COUNT, 
REVIEW_TEXT, SCORE, WRITE_DATE
) VALUES (
SEQ_REVIEW_ID.NEXTVAL, 2, 3, 1, 8, 
'생각했던 것보다 색상이 예쁘네요. 잘 쓰겠습니다.', 4, SYSTIMESTAMP - INTERVAL '1' DAY
);

INSERT INTO REVIEW (
REVIEW_ID, MEMBER_ID, OD_ID, REVIEW_STATUS, VIEW_COUNT, 
REVIEW_TEXT, SCORE, WRITE_DATE
) VALUES (
SEQ_REVIEW_ID.NEXTVAL, 2, 4, 1, 3, 
'무난합니다. 가격 대비 괜찮은 편이에요.', 3, SYSTIMESTAMP
);

INSERT INTO REVIEWIMAGE (REVIEW_IMAGE_ID, REVIEW_ID, REVIEW_IMAGE_ORIGINAL_NAME, REVIEW_IMAGE_SAVE_NAME, REVIEW_IMAGE_PATH, REVIEW_TITLE_IMAGE, REVIEW_IMAGE_CREATE_AT) 
VALUES (SEQ_REVIEW_IMAGE_ID.NEXTVAL, 1, 'towel_review.jpg', 'uuid_towel_review.jpg', '/upload/review/', 0, SYSDATE);

--------------------------------------------------
-- ADDREVIEW 확인용 ADMIN 더미 DATA 추가
--------------------------------------------------
INSERT INTO PRODUCTORDER (
    ORDER_ID, MEMBER_ID, TOTAL_PRICE, ORDER_STATUS, ORDER_DATE,
    USED_POINT, PAYMENT_ID, ADDRESS_NAME_FIX, DETAIL_ADDRESS_FIX
) VALUES (
    SEQ_ORDER_ID.NEXTVAL, 1, 35800, 'DELIVERED', SYSDATE - 2,
    0, 1, '관리자', '서울특별시 어드민구 테스트로 1'
);

INSERT INTO ORDERDETAIL (OD_ID, ORDER_ID, POP_ID, QTY, PRICE_FIX, GRADE_DIS_AMOUNT)
VALUES (SEQ_OD_ID.NEXTVAL, SEQ_ORDER_ID.CURRVAL, 1, 1, 35800, 0);

INSERT INTO DELIVERY (DELIVERY_ID, ORDER_ID, COMPANY, TRACKING_NO, DELIVERY_STATUS)
VALUES (SEQ_DELIVERY_ID.NEXTVAL, SEQ_ORDER_ID.CURRVAL, 'CJ대한통운', '999999999999', 'DELIVERED');


COMMIT;